"""Split user fullname column to firstname and lastname

Revision ID: 577322c3473a
Revises: 2bcf448044b0
Create Date: 2025-11-10 00:45:47.947810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577322c3473a'
down_revision = '2bcf448044b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=True))
        batch_op.drop_constraint(batch_op.f('user_fullname_key'), type_='unique')
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('user_fullname_key'), ['fullname'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
