"""update company model

Revision ID: d8cd4fcdfe75
Revises: 577322c3473a
Create Date: 2025-11-10 22:14:10.157943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8cd4fcdfe75'
down_revision = '577322c3473a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_balance_sheet', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fixed_assets', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_assets', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prepaid_expenses', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('equity_capital', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('provisions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('liabilities', sa.Float(), nullable=True))
        batch_op.alter_column('legal_form',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=40),
               nullable=True)
        batch_op.drop_column('industry')
        batch_op.drop_column('branch')
        batch_op.drop_column('revenue')
        batch_op.drop_column('employees_count')
        batch_op.drop_column('region')
        batch_op.drop_column('address')
        batch_op.drop_column('risk_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('employees_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('branch', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('industry', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.alter_column('legal_form',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('liabilities')
        batch_op.drop_column('provisions')
        batch_op.drop_column('equity_capital')
        batch_op.drop_column('prepaid_expenses')
        batch_op.drop_column('current_assets')
        batch_op.drop_column('fixed_assets')
        batch_op.drop_column('total_balance_sheet')

    # ### end Alembic commands ###
