"""updating company model

Revision ID: e7b11094ab5b
Revises: d8cd4fcdfe75
Create Date: 2025-11-12 01:14:50.760685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b11094ab5b'
down_revision = 'd8cd4fcdfe75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_sheet_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('intangible_assets', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tangible_assets', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('financial_assets', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stockpiles', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('receivables', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('securities_and_shares', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cash_and_bank_balances', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('equity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('required_share_capital', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('capital_reserves', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('retained_earnings', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('balance_sheet_profit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('profit_carried_forward', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('accruals', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('long_term_liabilities', sa.Float(), nullable=True))
        batch_op.drop_column('provisions')
        batch_op.drop_column('total_balance_sheet')
        batch_op.drop_column('equity_capital')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equity_capital', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_balance_sheet', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('provisions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('long_term_liabilities')
        batch_op.drop_column('accruals')
        batch_op.drop_column('profit_carried_forward')
        batch_op.drop_column('balance_sheet_profit')
        batch_op.drop_column('retained_earnings')
        batch_op.drop_column('capital_reserves')
        batch_op.drop_column('required_share_capital')
        batch_op.drop_column('equity')
        batch_op.drop_column('cash_and_bank_balances')
        batch_op.drop_column('securities_and_shares')
        batch_op.drop_column('receivables')
        batch_op.drop_column('stockpiles')
        batch_op.drop_column('financial_assets')
        batch_op.drop_column('tangible_assets')
        batch_op.drop_column('intangible_assets')
        batch_op.drop_column('balance_sheet_total')

    # ### end Alembic commands ###
